# Generated by Django 4.2.1 on 2023-07-08 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productvariant_quantity_in_stock_and_more'),
        ('coreapp', '0003_orderproduct_payment_remove_paymentmethod_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity_end_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_for_registered_users', models.BooleanField(default=False)),
                ('is_for_first_order', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category')),
                ('products', models.ManyToManyField(blank=True, to='product.product')),
            ],
        ),
    ]
