# Generated by Django 4.2.1 on 2023-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_remove_orderproduct_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(null=True),
        ),
    ]
