# Generated by Django 4.2.1 on 2023-07-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_coupons_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coreapp.payment'),
        ),
    ]
