# Generated by Django 4.2.1 on 2023-07-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_order_cancellation_reason_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
