# Generated by Django 4.2.1 on 2023-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
