# Generated by Django 4.2.1 on 2023-07-04 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
