# Generated by Django 4.2.1 on 2023-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
